project_id = "signet"

[db]
port = 54322
major_version = 15

[api]
port = 54321
schemas = ["public"]

[studio]
port = 54323

[auth]
enable_anonymous_sign_ins = true

[auth.hook.custom_access_token]
enabled = true
uri = "pg-functions://postgres/public/custom_access_token_hook"
